#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_large{1,0,16.12,0
#
idle.x28L: package/cfg/idle.x28L.mak

clean::
	-$(RM) package/cfg/idle.x28L.mak
